package ru.netology.domain.attachment;

public class Video {
    private int id;
    private int ownerId;
    private String title;
    private String description;
    private int duration;
    private int date;
    private int addingDate;
    private int views;
    private int localViews;
    private int comments;
    private String player;
    private String platform;
    private int canEdit;
    private boolean canAdd;
    private int isPrivate;
    private String accessKey;
    private int processing;
    private boolean isFavorite;
    private boolean canComment;
    private boolean canEditVideo;
    private boolean canLike;
    private boolean canRepost;
    private boolean canSubscribe;
    private boolean canAddToFaves;
    private boolean canAttachLink;
    private int width;
    private int height;
    private int userId;
    private boolean converting;
    private boolean added;
    private boolean isSubscribed;
    private int repeat;
    private String type;
    private int balance;
    private String liveStatus;
    private int live;
    private int upcoming;
    private int spectators;
    private LikesInfo likesInfo;
    private RepostsInfo repostsInfo;
}
